### ISSUE TITLE
Hide second CC and add organism to CC part of form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#10]
As per our discussions on the workbenches calls, we will remove the second CC from the CC section of the default form but then also add a slot for organism.

**Comment by tmushayahama** [comment]
Hidden the CC and added the placeholder for Organism. Working on adding the nested CC if needed

![image](https://user-images.githubusercontent.com/2273929/63388005-d84ee480-c35b-11e9-98f6-a48db092fb5b.png)

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
I've tested the feature and I think we're almost there.  We'll want to add a few more options to each level, though, as appropriate so that curators can add information as desired.

Here is what we'd want to add:

For 1st CC:
Add CC
Add Cell Type
Add Anatomy
Add Organism

For 2nd CC:
Add Cell Type
Add Anatomy
Add Organism

For Cell Type:
Add Anatomy
Add Organism

For Anatomy:
Add Organism

There would be no option to add anything more under Organism.

Also, for adding an Organism curators will need to use the syntax 'NCBITaxon:n' where n is one or more digits.  When I do this now, however, by adding 'NCBITaxon:6239', I don't see a corresponding node in the graph editor.  I can add this node via the 'Add Individual' function in the graph editor using autocomplete, though, so the information is in NEO?

**Comment by kltm** [comment]
This can be had from the usual NEO/go-lego endpoint you use for everything else. For example, by adding the filter `source: ncbi_taxonomy`.

**Comment by vanaukenk** [comment]
Looks good, @tmushayahama 

Just one last thing to do here - for CC 'part of' CC, move the 'Add CC' to the top of the list so that the extensions are listed in the correct hierarchy.  From above:

For 1st CC:
Add CC
Add Cell Type
Add Anatomy
Add Organism

Thanks!

**Comment by vanaukenk** [comment]
We also need to make sure they're displayed in the proper order, i.e. a second CC should always be displayed after the first CC.

**Comment by vanaukenk** [comment]
And we need to check on the resulting display in the table.  See the 'enabled by' mec-4 annotations in this model:
http://68.181.46.17:4201/workbench/noctua-form/?model_id=gomodel:5d88482400000052

**Comment by tmushayahama** [comment]
@vanaukenk hmm, I thought the model violated the cardinality constraint on multiple part ofs. Let me know if this is the case before I look more deeper. Or if this model was created by NF, then it will be a big bug on NF. Diagram below of

![image](https://user-images.githubusercontent.com/2273929/65632236-0a241e00-df8e-11e9-85cf-98abfea98047.png)

**Comment by vanaukenk** [comment]
@tmushayahama  This happened when I added a second CC after having added a cell.

Also, it looks like the CC annotations are not displaying correctly in the table, even when it's just a simple CC part_of cell.  The cell entry gets replicated multiple times and also gets a 'located in' relation.

![image](https://user-images.githubusercontent.com/1730534/65639534-4bc8bf00-dfb6-11e9-8637-cfe5e79f8f29.png)

**Comment by tmushayahama** [comment]
@vanaukenk ohh noo, thanks, i didn't even notice it, let me fix this. This happened after i put the menu For 1st CC:
Add CC
Add Cell Type
Add Anatomy
Add Organism

For 2nd CC:
Add Cell Type
Add Anatomy
Add Organism

so it was thinking it was on the first CC and duplicating everything and also I realized Cell Type is also an Uberon.

**Comment by tmushayahama** [comment]
@vanaukenk I just repeating issue and CL and Uberon issue. I haven't tested organism yet. Check if it is displaying well. However, the creation as described above of skipping and adding a node in between is not working and making wrong model. i.e. Adding Anatomy then adding Cell type. Will be fixing it soon

**Comment by vanaukenk** [comment]
Looks good now @tmushayahama !

![image](https://user-images.githubusercontent.com/1730534/65796499-cb7f9680-e13a-11e9-8100-fe254da7c5a6.png)

Thank you!

**Comment by vanaukenk** [comment]
@tmushayahama - It looks like skipping a CC extension and then adding it back is now making a correct model, even if the new extension line still just gets added to the bottom of the CC part of the form.

**Comment by vanaukenk** [comment]
Closing for now; I think this is fixed.
