### ISSUE TITLE
It seems that the wrong endpoint may be being used to import annotations

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua-form#101]
While tracking down an apparent issue for @suzialeksander we noticed that the "annotation import/search" seemed like it is using the wrong endpoint (noctua.berkeleybop.org), rather than the expected one (noctua.geneontology.org).

```./src/environments/environment.ts:29:  globalGolrCompanionServer: ' http://golr.berkeleybop.org/',```
``` ./src/environments/environment.prod.ts:23:  globalGolrCompanionServer: 'http://golr.berkeleybop.org/',```

Those should both be golr.geneontology.org (or equivalent). These should be using the global runtime context that contains this variable for this purpose: `global_golr_server`, so that this can be changed and coordinated.

https://github.com/geneontology/noctua-form/blob/078c9ae7b1273844194f17e2f2d73ed3c71a7bde/src/environments/environment.prod.ts#L23

**Comment by suzialeksander** [comment]
What lead to the issue: Trying to annotate Sc DBP1 (SGD:S000006040) in Form. 

Tried to use the three dots dropdown ->Search Annotations to incorporate an existing annotation (either GO:0033677 DNA/RNA helicase or GO:0016887 ATPase, made in P2GO on 2019-12-13) . We can’t find those in Form (dev or production), but they do appear in AmiGO, SGD, Protein2GO as well as import/export GAFs.

**Comment by kltm** [comment]
@tmushayahama 
For historical reasons, NEO is `global_golr_neo_server` and the "regular" amigo/golr (for annotation import and nothing else) is `global_golr_server`.

**Comment by vanaukenk** [comment]
@tmushayahama @suzialeksander 

This looks to be fixed in production, so I'm closing the ticket. 

Feel free to re-open if you find new, related issues.  Thx.
