### ISSUE TITLE
Side Menu on the form

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#107]
Most features like clone evidence, are frequently used but it involves 3 clicks in a nested side menu. 
Ideas to (flatten nested menu)?

![image](https://user-images.githubusercontent.com/2273929/86321063-18722b00-bbed-11ea-8d36-edac9321c36c.png)

**Comment by vanaukenk** [comment]
Will close this for now.  We can revisit if we get more feedback about improving this from curators.
