### ISSUE TITLE
Has Part, Sub Function

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#11]
From this issue https://github.com/geneontology/go-shapes/issues/52 and today's GO CAM discussion, how does NF integrate all this to the current state? 

- Current causal relationship editor
- Creation of new activities
- Reading already created models with has_part
- Extra Operations, Validation and Deletion

tagging @vanaukenk @pgaudet @thomaspd

**Comment by vanaukenk** [comment]
@tmushayahama 

We will need to update the MF section of the form to allow curators to add sub-functions using the 'has part' relation.

I'll work on the specs for this and we can discuss on a future call.

**Comment by vanaukenk** [comment]
@tmushayahama
I'm going to close this ticket as I think it actually touches on several different issues that either are, or should be, captured in separate tickets.
