### ISSUE TITLE
Reading enabled by Protein Containing Complex

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#111]
@vanaukenk 

I was chatting with @goodb and @kltm on Gitter and realized Noctua Form is not reading enabled by Complexes according to shex

![image](https://user-images.githubusercontent.com/2273929/88118245-03484680-cb72-11ea-84d1-ffa4d7197f86.png)

The result is ignored value of Complex like so 

![image](https://user-images.githubusercontent.com/2273929/88118468-7fdb2500-cb72-11ea-8b72-b185db03ef2a.png)

What should I do in this case?

**Comment by vanaukenk** [comment]
Discussed on 2020-07-22 workbenches call:

We will allow 'enabled by' protein-containing complexes that do not use the GO namespace.

For example, ComplexPortal:CPX-1791 would be allowed for 'enabled by' but GO:1990298 bub1-bub3 complex would not be allowed.

Note that this is a more general issue than just how the Noctua Form works.  We'll want to discuss strategy further with @goodb especially in the context of constructing NEO.

Also, consider always populating 'enabled by' even if just with a default 'root' term like 'InformationBiomacromolecule'

**Comment by goodb** [comment]
@vanaukenk I think it would be much better to use an ontology term differentiator instead of a namespace.  We shouldn't be doing anything here that we can't represent in OWL / shex.  What is the semantic difference between ComplexPortal:CPX-1791 and GO:1990298 bub1-bub3 complex ?  What terms can we use to make the discrimination ?

**Comment by vanaukenk** [comment]
Thanks for your input @goodb 

I agree that an ontology term differentiator would be the best approach here, but unfortunately I don't think we currently have one, so perhaps the best solution at this point would be to allow, in Noctua, any 'protein-containing complex' to enable an MF, but educate curators so they're aware that we don't want GO protein-containing complexes as enablers in GO-CAMs, as these represent classes of protein-containing complexes, not specific instances of a protein-containing complex.

**Comment by goodb** [comment]
@vanaukenk what you are saying is a change to the schema that, if that is the decision, we should carry out.  Right now we have
```
<MolecularFunction>
  enabled_by:  ( @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) {0,1};
```
with ProteinContainingComplex being the one from the GO CC branch.  It sounds like what you want to do is change that to 
```
<MolecularFunction>
  enabled_by:  ( @<InformationBiomacromolecule> ) {0,1};
```
and then, in NEO, have Complex Portal entries typed as InformationBiomacromolecules and not as complexes.  This is, to my confusion, actually how NEO represents things already.  There is a related open ticket regarding NEO and URIs https://github.com/geneontology/neo/issues/17 - if what I am saying above makes sense, we should make sure that the complex portal entities stay classified as information molecules and not GO complexes whenever we get around to updating the NEO build. 

There are a few other places in the schema where we have 
```
( @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) {0,1};
```
transports_or_maintains_localization_of: in transporter activity and BP, location_of in AnatomicalEntity
Should these be changed as well?

----
FWIW I am trying my best to simply take the decision you folks made and move things forward.  But, from my outside view, saying that an entity that is called a complex from a resource called complex portal is in fact not a complex from the perspective of the GO is pretty hard to understand.  Perhaps the GO term 'protein-containing complex' needs some kind of a new name that more accurately reflects its intended meaning.

**Comment by vanaukenk** [comment]
@goodb 

I think what you've just written might have completely clarified some things for me.

So, even if a complex is represented in a group's gpi file as a type of GO:0032991 'protein-containing complex', for the purposes of NEO, that complex is typed as an 'InformationBiomarcomolecule'?

If that's the case, then at least for the 'enabled by' values, what we have in NEO right now is fine and I think we could just remove 'ProteinContainingComplex' from the ShEx.

I was thinking that, in NEO, protein complexes were typed as GO:0032991.

For the other cases, like 'transports_or_maintains_localization_of', the same thinking should probably apply.

One concern here is that many groups may not have internal or ComplexPortal IDs for their protein complexes, but we could encourage them to either mint them or collaborate with IntAct to create them.

**Comment by goodb** [comment]
@vanaukenk I don't know that this is a general rule for how the NEO build works or not.  I would hope that NEO would respect any classifications added to a GPI file (or GPI ontology..).  That being said, I don't see any entries in NEO that are classified as GO:0032991 right now.  All complex portal entries are infobio - e.g. http://noctua-amigo.berkeleybop.org/amigo/term/ComplexPortal:CPX-4082

**Comment by goodb** [comment]
> One concern here is that many groups may not have internal or ComplexPortal IDs for their protein complexes, but we could encourage them to either mint them or collaborate with IntAct to create them.

We faced this with Reactome for the go-cam conversion.  I think the best long term solution we found (after long struggle) is integration and collaboration with PRO.

**Comment by ukemi** [comment]
In the new GPI spec, the object type (column 5) for these is the GO protein-containing complex and it is also the parent of protein complexes in PRO. In fact, PRO uses the GO sub-classification for classification of species-specific complexes.

[Term]
id: PR:000024949
name: Cecr2:SNF2H complex (mouse)
def: "An ISWI-type complex of Cecr2 and SNF2H that is encoded in the genome of mouse." [PMID:22154806, PRO:KRC]
comment: Category=organism-complex.
is_a: GO:0031010 ! ISWI-type complex
relationship: only_in_taxon NCBITaxon:10090 ! Mus musculus
relationship: has_component PR:E9Q2Z1 ! cat eye syndrome critical region protein 2 homolog (mouse)
relationship: has_component PR:Q91ZW3 ! SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A member 5 (mouse)

**Comment by ukemi** [comment]
We could instantiate them in the models for groups that don't have ids. @goodb?

http://noctua.berkeleybop.org/editor/graph/gomodel:5ee8120100002360?model_id=gomodel:5ee8120100002360

**Comment by vanaukenk** [comment]
In the current gpi 1.2 files that groups submit, if there are ids for protein-containing complexes, the corresponding DB Object Type field just says 'protein_complex'.  

So does that mean that the current behavior for building NEO types everything in a gpi 1.2 file as an InformationBiomacromolecule?

As @ukemi says, our gpi 2.0 spec types protein complex entries with the GO id GO:0032991, but it seems we either need a new protein-containing complex type term (as @goodb suggests above) or we type protein-containing complexes in gpi 2.0 as InformationBiomacromolecule to avoid collision with GO protein-containing complex terms as potential enablers.

As for what id space annotating groups should use to mint new protein-containing complexes, I think that is a broader discussion that should happen amongst all the interested parties.

**Comment by ukemi** [comment]
or in the Shex we specify that they have to be a (GO_0032991 AND only_in_taxon SOME NCBITaxon_1)?

**Comment by goodb** [comment]
@ukemi I think we want an actual class from an ontology to refer to for these things.  I don't think we want to make instances in models sometimes and other times refer to neo or pro or other ontology classes for the same kinds of things.  Like with Reactome, I think the definitions of these classes should happen in an ontology one way or another, not in the model.

**Comment by vanaukenk** [comment]
For purposes of discussion and making sure we thoroughly review all references to a ProteinContainingComplex in the ShEx, here are all of the shapes that currently make use of ProteinContainingComplex (defined as GO_0032991 for now).

We need to decide which of these uses of ProteinContainingComplex can stay, which should be replaced with an ontology class that is a parent to species-specific annotatable complex entities, and where we might want to allow both.

```
<BiologicalProcess> @<GoCamEntity> AND EXTRA a {
  a ( @<BiologicalProcessClass> OR @<NegatedBiologicalProcessClass> ) {1};
  has_input: ( @<ChemicalEntity> OR @<AnatomicalEntity> OR @<ProteinContainingComplex> ) *;
  has_output: ( @<ChemicalEntity> OR @<AnatomicalEntity> OR @<ProteinContainingComplex> ) *;
  transports_or_maintains_localization_of: ( @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) *;
```

```
<Localization> @<BiologicalProcess> AND EXTRA a {
  a @<LocalizationClass> {1};
  transports_or_maintains_localization_of: ( @<AnatomicalEntity> OR @<ChemicalEntity> OR @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) *;
```

```
<ProteinContainingComplexRemodeling> @<BiologicalProcess> AND EXTRA a {
  a @<ProteinContainingComplexRemodelingClass> {1};
  results_in_remodeling_of: @<ProteinContainingComplex> {0,1};
```
```
<MolecularFunction> @<GoCamEntity> AND EXTRA a {
  a ( @<MolecularFunctionClass> OR @<NegatedMolecularFunctionClass> ) {1};
  enabled_by:  ( @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) {0,1};
  has_output: ( @<ChemicalEntity> OR @<ProteinContainingComplex> ) *;
  has_input: ( @<ChemicalEntity> OR @<ProteinContainingComplex> ) *;
```
```
<TransporterActivity> @<MolecularFunction> AND EXTRA a {
  a @<TransporterActivityClass> {1};
  transports_or_maintains_localization_of: ( @<ChemicalEntity> OR @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) *;
```
```
<AnatomicalEntity> @<GoCamEntity> AND EXTRA a {
  a ( @<AnatomicalEntityClass> OR @<NegatedAnatomicalEntityClass> );
  location_of: ( @<InformationBiomacromolecule> OR @<ProteinContainingComplex> ) {0,1};
```

```
<ProteinContainingComplex> EXTRA a {
  a @<ProteinContainingComplexClass>;
  located_in: @<AnatomicalEntity> {0,1};
  has_part: @<InformationBiomacromolecule> *;
```

```
<Protein> @<ChemicalEntity> AND EXTRA a {
  a @<ProteinClass> ;
  located_in: @<AnatomicalEntity> {0,1};
  part_of: @<ProteinContainingComplex> {0,1};
```

```
<InformationBiomacromolecule> @<ChemicalEntity> AND EXTRA a {
   a @<InformationBiomacromoleculeClass> +;
   located_in: @<AnatomicalEntity> {0,1};
   part_of: @<ProteinContainingComplex> {0,1};
```

**Comment by vanaukenk** [comment]
This still looks to be an issue, at least for human ComplexPortal entities, and I'm not sure why.   See the top row of the Noctua form table screenshot below. 

I also tested protein-containing complexes from the SGD and MGI gpi files which are submitted as formats 1.2 and 2.0, respectively, and they display properly in the Noctua form table.

![image](https://user-images.githubusercontent.com/1730534/142227348-21dc7105-a61c-4703-b459-a803557cffa9.png)

@kltm @cmungall @balhoff - any insight into why, specifically, it's the human complex portal entry that won't display in the Noctua form table?

**Comment by balhoff** [comment]
@vanaukenk I wonder if my recent NEO change will help here? https://github.com/geneontology/neo/pull/81

**Comment by vanaukenk** [comment]
@balhoff 

I will test this after tomorrow's update.  Thx.

**Comment by vanaukenk** [comment]
See: https://github.com/geneontology/noctua-form/pull/164

**Comment by vanaukenk** [comment]
I *think* everything is working okay now here.
If we find new issues, we can create new tickets.
