### ISSUE TITLE
noctua-dev 'Remove evidence' is removing all evidence boxes instead of just the values 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#117]
From 2020-09-23 call:

![image](https://user-images.githubusercontent.com/1730534/94052416-ebc24f80-fda6-11ea-95c1-5d3e61c87529.png)

Screenshot of MF fields after curator clicked on 'Remove evidence'

**Comment by tmushayahama** [comment]
@vanaukenk I found the bug and have fixed it, Will PR soon. It was the NF client's fault. Sorry for the inconveniences, it wasn't minerva.

I had forgotten to specify which evidence number (in array) to remove, so it was just blanking out.

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
Feel free to PR when you're ready and I will test again.

**Comment by vanaukenk** [comment]
If only one line of evidence, the behavior should be that a curator can clear the values, but not remove the entire line of evidence.

**Comment by vanaukenk** [comment]
Closing this ticket as it appears to be working as expected on production.
