### ISSUE TITLE
 Noctua form : deleting an annotation not working

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua-form#120]
Tried some annotation and then wanted to delete it in form, but the delete button did nothing. Then went to graph editor to delete it. Strange. 

I also don't find it intuitive to go back to form once you have been in graph editor. Seems one way. First form then stay in graph editor.

**Comment by pfey03** [comment]
@vanaukenk But then the form is not really useful, at least for me. You can start with form but once you are in graph editor it's not really practical to go back to form adding more annotations there. Bob and I collaboratively tried things out the other day and found the form ultimately quite useless.

**Comment by pfey03** [comment]
I should add, the form then is just a way to look at annotations in tabular form, which is fine.

**Comment by vanaukenk** [comment]
@pfey03   I'd be interested to hear more details about your and Bob's experiences.

We've been a bit concerned that a delete action on the form could result in deleting connected nodes and wanted to make sure that users would be fully aware of what was happening when they delete something and therefore should do this on the graph editor (at least right now).

The Noctua form and graph can serve different curation purposes.  I actually use both depending on what I'm doing.

**Comment by pfey03** [comment]
@vanaukenk We thought yes, doing different things in form and graph, but going back to form and doing something there is not easy. Also we noticed that one graph does not produce one form but two or more. A small graph and not finished by any means already produced two. I put the annotations we did also for discussion on Tuesday as we have a specific annotation question as well.
