### ISSUE TITLE
References when importing MGI annotations

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua-form#123]
As part of an effort to model metabolic pathways in GO-CAM, it is extremely useful to be able to import existing annotations. However, when I tried to import an MGI annotation using the form yesterday, the imported annotations included the MGI reference identifier instead of a Pubmed identifier. The resulting GPAD output only contained the MGI identifier. Currently these would fail our load scripts (not a big deal immediately because the annotations already exist in MGI). We should import conventional annotations into models exactly the way we are importing conventional annotations in the 'legacy load' project. We should include a discussion of this in our overall data flow strategy. I can demonstrate the behavior on a call.

**Comment by vanaukenk** [comment]
Please also see this ticket here:  https://github.com/geneontology/noctua/issues/410

@tmushayahama @lpalbou  - let's discuss on a workbenches call how the data is stored vs retrieved to see how easy/hard a fix would be here.

**Comment by vanaukenk** [comment]
Discussed with @tmushayahama 
When there are multiple references, e.g. a MOD paper id and a PMID, it will be easier to display and import both references into the Noctua form.

**Comment by vanaukenk** [comment]
See also #119

**Comment by vanaukenk** [comment]
For papers, we'll display both ids, pipe-separated.

**Comment by tmushayahama** [comment]
I have separated by a "|" Any special occasion with an & separator or ','?

![image](https://user-images.githubusercontent.com/2273929/100678024-1be71b00-3321-11eb-9bab-2ae62721d090.png)

tagging @ukemi @vanaukenk

**Comment by vanaukenk** [comment]
Related issue:  https://github.com/geneontology/gocamgen/issues/31

But we still need to agree on best behavior for now for importing existing annotations.

**Comment by ukemi** [comment]
Just noticed this again. How do we want to export these in a GPAD?
