### ISSUE TITLE
Allow Save in BP only form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#13]
Currently, the BP only version of the form is not allowing me to save an annotation and gives this error message:

![image](https://user-images.githubusercontent.com/1730534/64191988-b3706c00-ce47-11e9-9cbe-997e7cae2b43.png)

even when root MF is automatically entered.

**Comment by tmushayahama** [comment]
I think this has been fixed. Also now Biological Process is required for the BP only form

**Comment by vanaukenk** [comment]
Almost there :-)

The BP only version of the form allows curators to save even when they haven't specifically picked a relation from the drop-down menu.
We should require curators to select a relation from the menu before they can save.
