### ISSUE TITLE
Update Cellular Component only (CC only) form to reflect new gp2term relations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#130]
We need to update the CC only implementation of the Noctua form to accommodate the new default gp2term relations.

This is a placeholder ticket for now with detailed requirements coming once the higher levels of the CC ontology are completely worked out.

**Comment by vanaukenk** [comment]
We need to update the CC annotation only form in the following way:

GP part_of protein-containing complex (GO:0032991)
GP located_in anatomical entity (CARO:0000000)
GP is_active_in anatomical entity (CARO:0000000) OR root cellular component (GO:0005575)

Proposal:
Create a separate annotation line for each possible gp2CC annotation with the specified relation.
Only the 'is active in' annotation line would have the ability to add a root node annotation.

@tmushayahama @ukemi

**Comment by ukemi** [comment]
I'm not sure I understand the second part of the proposal. Is it to accommodate for the default root node CC annotations, where we had decided that would be the default?

**Comment by vanaukenk** [comment]
@ukemi 

> Is it to accommodate for the default root node CC annotations, where we had decided that would be the default?

Yes; we can review on the workbenches call

**Comment by vanaukenk** [comment]
From 2021-06-18 call:

We agreed to have a relation box, followed by an ontology term box.  Selecting the former will determine what is available in the latter. 

GP part_of protein-containing complex (GO:0032991)
GP located_in anatomical entity (CARO:0000000)
GP is_active_in anatomical entity (CARO:0000000) OR root cellular component (GO:0005575)

**Comment by vanaukenk** [comment]
From 2021-06-25:
Curators will need to select each option multiple times, if they want. @tmushayahama 

Still need to discuss how to model the localization data behind the scenes, i.e. do we want to model located_in as:  enabled_by GP <- root MF -> occurs_in CC

@ukemi @lpalbou @cmungall @thomaspd

**Comment by vanaukenk** [comment]
Discussed modeling 'located in' with @ukemi 

We agree that when a curator chooses 'located in' to describe the subcellular localization of a gene product they are making a statement solely about localization without necessarily making a statement about molecular function, i.e. they're capturing where a gene product may be found but not making a statement about whether it might have _any_ molecular function in that location.

For that reason, we think it's still best to model these annotations as: gene product 'located in' cellular anatomical entity without any statement about molecular function.

Note that curators should strive to capture the subcellular location where a gene product is active by creating an activity unit, but in cases where they only want to capture localization, we'll model it as stated above.

@tmushayahama @lpalbou

**Comment by vanaukenk** [comment]
Two more small updates to the CC only form from 2021-07-15 call:

1. Change 'Function Description' text in blue box -> 'Localization Description'
2. Make sure that all CC annotations added via the CC only form appear underneath that box (i.e. protein-containing complex annotations are not separate from cellular anatomical entity annotations)

**Comment by ukemi** [comment]
I attempted to add a CC only annotation by entering a GP, selecting the 'is located in' option, and typing in 'pyruvate kinase complex'. The form did not autocomplete the complex, but it did let me save the annotation, but it is incomplete. Also note this should not happen. We should not be allowed to enter an 'is located in' annotation with a protein complex. 
See the BMP4 HSAP annotation in this model: gomodel:60f9f1ad00000007

**Comment by vanaukenk** [comment]
@tmushayahama 
The nice checks that you have in the activity unit form (i.e. a curator has to fill in all of the required fields before they can save the annotation) should also be in the CC only form.

**Comment by vanaukenk** [comment]
@tmushayahama 

Here is the [spreadsheet](https://docs.google.com/spreadsheets/d/15XxajKRLcgTSqQ3LBqS1AMCFl1ak5FuFunLDo_PsBCY) with the testing that @ukemi and I have done so far.  Can you take a look and let us know if/where you might need more information and if these bug fixes or enhancements are easy or hard?  

It'd be good to use Friday's workbenches meeting to prioritize any remaining work on this and other, related tickets.

Thanks.

**Comment by tmushayahama** [comment]
@ukemi @vanaukenk I made comments on the spreadsheet. It seems like all the autocompletes are working I tried pyruvate kinase complex and nucleus and they completed. I will be making revisiting the error handling and  the 'not' complement

**Comment by ukemi** [comment]
@tmushayahama  I will try to repeat my autocomplete issue. If it happens again, maybe we can meet and I can share my screen. I am using Firefox on a Mac. Could it be a browser issue?

**Comment by tmushayahama** [comment]
@ukemi I just tried with firefox and it seems to be working (even without space). Lemme know

![image](https://user-images.githubusercontent.com/2273929/127345128-67c2aeed-7008-43f1-bf85-5dfae8a6adab.png)

**Comment by ukemi** [comment]
@tmushayahama Do you have a few minutes to meet so I can share my screen?

**Comment by tmushayahama** [comment]
I have sent you an email

**Comment by vanaukenk** [comment]
2021-08-20 call:

We agreed that, for now, we will not offer the 'is active in' option on the CC only form.  

If curators want to make that gene product-to-term statement, they can use the Create Activity form which will capture the annotations according to the GO-CAM data model and export appropriately in the GPAD.

**Comment by vanaukenk** [comment]
@tmushayahama 
I'm testing the updated CC only form on noctua-dev and found one bug.

If I create two rows of annotation and then select Clear Values on the second row, the values disappear on the form, there is only one entry in the table, but the graph editor still displays a second node for the gene.  

Here are two examples:

![image](https://user-images.githubusercontent.com/1730534/130489395-d1289491-0365-43af-b3dd-aece42470f95.png)

We don't want the stand-alone node for nipi-3 and scav-5 in these two examples.

**Comment by tmushayahama** [comment]
@vanaukenk thanks, yeah this is a bug. I was only testing one way. Lemme look at it

**Comment by vanaukenk** [comment]
Will open a new ticket for display on the Noctua form table.
