### ISSUE TITLE
Form With/from multiple values issues

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua-form#139]
We've had some issues making de novo annotations with multiple entries in the with/from field.  The annotations aren't showing in Annotation Preview (no line, nothing) and i had a popup about datatables.  I can't reproduce but it's happened several times, most recently 

gomodel:60e7989d00000730
gomodel:60e7989d00000724
gomodel:60e7989d00000718

BUT we fixed these yesterday and now can't re-break them. Is there model history you can roll back?  Possibly it's something to do with commas/pipes/spaces?

One issue is the teensy with/from field, I suspect we can't tell if we've formatted properly in Form as the field is only exactly long enough for an SGD ID no punctuation, anything longer wraps around.

<img width="704" alt="Screen Shot 2021-07-21 at 3 09 55 PM" src="https://user-images.githubusercontent.com/13735608/126566706-d6b372c6-1823-479f-8de9-df06461dc32c.png">
<img width="704" alt="Screen Shot 2021-07-21 at 3 10 09 PM" src="https://user-images.githubusercontent.com/13735608/126566712-cf32b881-74fd-4d4f-bce9-5e5fe97eea91.png">

Also, since yesterday the with/from field is finally translating SGD IDs (SGD:S000002292) to the human-readable name (PPH21), except refuses to translate PPH21 - SGD:S000002292 , see http://noctua.berkeleybop.org/editor/graph/gomodel:60e7989d00001392

PPH21 is not a new name and has been stable for quite some time.  Not sure if this is related to the first issue I can't reproduce.

**Comment by vanaukenk** [comment]
Moving to noctua-form tracker; we can continue working on it there.

**Comment by vanaukenk** [comment]
@suzialeksander @ukemi @tmushayahama 
I'm starting on some systematic testing in the form.  I'll update this ticket when there's more info.

**Comment by ukemi** [comment]
Maybe relevant:  https://github.com/geneontology/minerva/issues/398

**Comment by vanaukenk** [comment]
@suzialeksander @ukemi @tmushayahama 

The With/From field in Noctua (both form and graph) is currently very liberal.  Curators can enter any text and the form will take exactly what they've entered.  But, unfortunately that  makes it easier than we'd like to enter something incorrect by mistake. See a bunch of my tests here:

![image](https://user-images.githubusercontent.com/1730534/126662275-f7775a9d-623a-4fc4-bdb6-609e2721f1e7.png)

@suzialeksander take a look at the With/From field entries in your model in the graph editor or the form table to see if the formatting is always what you intended.  If it is, and you're still not seeing what you want, let's follow up some more.

Wrt what is being displayed in the With/From field in the Annotation Preview, I'm afraid I don't have insight there.  At least some of the C. elegans genes I added in the With/From field should be resolvable to a label, but they weren't when I was testing.  We'll have to follow up with @balhoff about that.

@tmushayahama - in the past, we've discussed formatting the With/From field into two separate boxes, the first being a prefix box and the second the actual id.  That would help somewhat, but we'd also then need to add functionality for curators to specify multiple entries with commas vs pipes.  Perhaps in the meantime, a bigger With/From field on the form would really help curators to at least view more easily what they've added and check for correct syntax.

**Comment by suzialeksander** [comment]
<img width="665" alt="Screen Shot 2021-07-22 at 9 09 45 AM" src="https://user-images.githubusercontent.com/13735608/126672367-b154c89a-a663-47fb-86a8-746f0b3c7fef.png">

By not translating, I mean the SGD ID for PPH21, which I entered as SGD:S000002292, remains SGD:S000002292 in the preview even though the others are displayed as PPH2,  etc. even though I entered those as SGD IDs in Form.

**Comment by vanaukenk** [comment]
@suzialeksander 

I understood what you meant by 'not translating' but I wasn't sure about the formatting of all the With/From entries here, e.g. some seem to have a comma, while others don't.  If there'll all formatted exactly the same way, what happens then?

For the details of the translation code, though, @balhoff or maybe @kltm would have to shed some light there.

**Comment by suzialeksander** [comment]
this was a test case trying to recreate the 'datatables' warning.  The real models created by Rob seem to work with `SGD:S000002482,SGD:S000002347` and is producing Annotation Previews, but I can't check Snapshot yet (we fixed these on the 20th and snapshot is from the 20th)

**Comment by vanaukenk** [comment]
Okay, once you've tested snapshot, let us know if there's still an issue.
Thanks.

**Comment by vanaukenk** [comment]
From 2021-07-30 workbenches call:
We'll first try giving the With/From field more real estate on the form to see if that helps.
Other future options might include:
1) An editing pop-up to help with formatting and data entry
2) Changing the layout of the form and table to give more horizontal space to each.

**Comment by vanaukenk** [comment]
Yes, longer strings of With/From values are difficult to view and/or edit in the With/From field in the form.

**Comment by ukemi** [comment]
Actually, they are easy to enter because the box opens up. When you're done editing they collapse into the smaller box.

**Comment by vanaukenk** [comment]
In general, I think we need to think some more about how we enter With/From values on the Noctua-form.  @tmushayahama had some nice new prototypes on his development server, IIRC.
Let's re-visit at some point.
