### ISSUE TITLE
Add brief annotation summary to Noctua form table view for easy browsing

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#146]
@tmushayahama @ukemi 

From our 2021-09-03 workbenches call, we think it would be helpful for curators to see a brief summary statement of what is contained in each of the table entries by listing the GO terms and relations.  This will help curators with big models get a quick overview of what is in the model without having to 'open all'.

Here's a q&d mock-up to get us started:

![image](https://user-images.githubusercontent.com/1730534/132064203-41ae54f3-df76-4a67-938c-cc1436863568.png)

**Comment by vanaukenk** [comment]
@ukemi - see https://github.com/geneontology/noctua-form/issues/155

Wrt the circles in the logo, @tmushayahama reminded me that they're an indication of the form used, not the completeness of the activity unit.  Perhaps we can brainstorm some more about this feature to make it clearer.

**Comment by ukemi** [comment]
Ah ok. That makes sense. Maybe just reomve? Yes, let's brainstrorm.

**Comment by vanaukenk** [comment]
One more thing to add (from 2021-11-19 workbenches call):
Fill in CC circle when CC only form is used to make the GP part_of protein-containing complex (GO:0032991) statement.

**Comment by vanaukenk** [comment]
For 2022-02-24 workbenches call, let's review this test model:

http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A60ad85f700000819

**Comment by vanaukenk** [comment]
Issue with showing protein-containing complexes on the summary is not fixed yet on dev:

http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A621fffab00000023

**Comment by vanaukenk** [comment]
Closing this ticket for now, but noting that a protein-containing complex annotation does not result in a filled-in CC circle.  We may need to re-visit this, if curators would like this information displayed in some way.
