### ISSUE TITLE
Assigned_by blank in "Search Annotations" popup

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua-form#147]
In Form, when the Search Annotations field has been selected, we would like to only import SGD annotations but the `ASSIGNED BY` field is blank: 
![image](https://user-images.githubusercontent.com/13735608/132070283-f5b107d9-aad0-45a3-be3f-ae7b0475531a.png)

Don't think this is related to https://github.com/geneontology/noctua-form/issues/38, which looks solved??

**Comment by vanaukenk** [comment]
Done.
