### ISSUE TITLE
Activity line jumps when Edit icon used

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua-form#151]
I think we've reported similar before, but can't find the ticket.  Trying to edit a line using the pencil icon, and the line "jumps" without letting the user edit.  Tried to add a screen recording.

Seems like saving between edits, or immediately before using the pencil icon, makes the Form behave again without jumping.  

keywords in case I lose this issue again: jump flip hops flipflop erratic 

https://user-images.githubusercontent.com/13735608/135532371-9ba6bb13-d2a8-4e6a-b597-29aa1fc8e88f.mov

o

**Comment by tmushayahama** [comment]
Hi @suzialeksander thanks, I haven't seen this before. What browser are you using? Is there a yellow popup coming out? Something like below

![image](https://user-images.githubusercontent.com/2273929/135546116-ea8ee7f6-e917-4283-9af8-5187b2417c06.png)

**Comment by suzialeksander** [comment]
This was on FF 92.0.  No popup, it never offered the ability to edit.  I think I edited through GE once without issue when Form was doing this.  Rob was also on FF, 92.0.1 and found it stopped jumping if he saved, then made ONE edit, then saved again.  Can't do multiple edits.

**Comment by vanaukenk** [comment]
I just tested this again on Chrome and it's working okay there.

**Comment by vanaukenk** [comment]
Closing this for now; no action taken.
@suzi If this continues to be a problem, please let us know.
