### ISSUE TITLE
Add 'existence overlaps' and 'existence starts and ends during' as valid CC extension relations in the form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#152]
We've updated the annotation extension relations that can be used to describe when a CC exists.
We now use 'existence overlaps' and 'existence starts and ends during'.
Curators would like to be able to add these extensions in the form (they are already available in the graph editor).

Here are the entries in gorel with the domain and range constraints:

id: existence_overlaps
name: existence overlaps
def: "x existence overlaps y if and only if either (a) the start of x is part of y or (b) the end of x is part of y. Formally: x existence starts and ends during y iff (α(x) >= α(y) & α(x) <= ω(y)) OR (ω(x) <= ω(y) & ω(x) >= α(y))" []
comment: The relations here were created based on work originally by Fabian Neuhaus and David Osumi-Sutherland. The work has not yet been vetted and errors in definitions may have occurred during transcription.
subset: AE_biological_process
subset: AE_developmental_stages
subset: display_for_curators
subset: valid_for_annotation_extension
xref: RO:0002490
property_value: IAO:0000117 "Chris Mungall" xsd:string
property_value: local_domain BFO:0000004 xsd:string
property_value: local_range "GO:0008150 WBls:0000075 ZFS:0100000" xsd:string
property_value: usage "Identifies a process or life stage during which a cellular component is present" xsd:string
is_a: go_annotation_extension_relation ! go annotation extension relation
is_a: relation_between_physical_entity_and_a_process_or_stage ! relation between physical entity and a process or stage

[Typedef]
id: existence_starts_and_ends_during
name: existence starts and ends during
def: "x exists during y if and only if: 1) the time point at which x begins to exist is after or equal to the time point at which y begins and 2) the time point at which x ceases to exist is before or equal to the point at which y ends. Formally: x existence starts and ends during y iff α(x) >= α(y) & α(x) <= ω(y) & ω(x) <= ω(y) & ω(x) >= α(y)" []
comment: The relations here were created based on work originally by Fabian Neuhaus and David Osumi-Sutherland. The work has not yet been vetted and errors in definitions may have occurred during transcription.
subset: AE_biological_process
subset: AE_developmental_stages
subset: display_for_curators
subset: valid_for_annotation_extension
synonym: "exists during" EXACT []
xref: RO:0002491
property_value: IAO:0000117 "Chris Mungall" xsd:string
property_value: local_domain BFO:0000004 xsd:string
property_value: local_range "GO:0008150 WBls:0000075 ZFS:0100000" xsd:string
property_value: usage "Identifies a process or life stage during which a cellular component is present" xsd:string
is_a: existence_ends_during ! existence ends during
is_a: existence_starts_during ! existence starts during
is_a: go_annotation_extension_relation ! go annotation extension relation

**Comment by tmushayahama** [comment]
@vanaukenk what is the cardinality of these. Also these are extending CC node correct? Or extending MF node?

**Comment by vanaukenk** [comment]
@tmushayahama 

These annotation extensions only extend CC nodes.  Their parent relation in RO is: 'relation between physical entity and a process or stage'.

In theory, a curator could add more than one existence extension to a CC, e.g. a GO BP phase and an animal lifestage phase.
In practice, I don't know how often that will happen, though.

I'll update the ShEx for these extensions, since they aren't there yet.

Let me know if you need more info or want to chat.

**Comment by tmushayahama** [comment]
Thanks @vanaukenk also, what will be the label of each of the object of (WBls:0000075 ZFS:0100000) i.e. CC existence_overlaps (BP, ?, ?) and CC existence_starts_and_ends_during  (BP, ?, ?). As in what should be on the extension menu

![image](https://user-images.githubusercontent.com/2273929/135915762-d7f1794b-2c5b-4ea1-afe5-eb99e42b77ab.png)

**Comment by vanaukenk** [comment]
@tmushayahama 
Is this just for display?
If so, we could just , for example, say: 'Add existence overlaps (BP, Phase, or Stage)'

**Comment by vanaukenk** [comment]
@tmushayahama 
Just confirming that these extensions can be used with all CC terms, including protein-containing complex and its children.

**Comment by vanaukenk** [comment]
This appears to be working fine in the Noctua form for the WB and ZFIN developmental stage terms, but I'm not sure it's working in the form for mouse or Xenopus developmental stage terms.

@ukemi - can you double-check for mouse when you have a minute?  Thanks.

**Comment by ukemi** [comment]
It looks like the Theiler stages are not working. @balhoff if you have a minute at some point, we can look together or just try to use one, TS12.

**Comment by balhoff** [comment]
TS12 is now under 'life cycle stage' in go-lego. @tmushayahama are there some other constraints that might stop it form appearing? I also can't find 'adult frog stage' in the form editor, which is also in the right place in go-lego.

**Comment by vanaukenk** [comment]
That's right - we are missing mouse and frog life stages in the form, but we do have worm and fish.

**Comment by vanaukenk** [comment]
For Theiler stages, the top level 'Theiler stage' id is:  TS:0
and for XAO, the top level developmental stage is: XAO:1000000

**Comment by vanaukenk** [comment]
2021-11-05 - noctua-dev will be updated with the fix to look for all children of UBERON:0000105.
@ukemi - we tested on @tmushayahama local instance, but feel free to double-check on noctua-dev before we put onto production noctua.

**Comment by ukemi** [comment]
If I try to create a new CC annotation in the form, I still cannot add an existence overlaps annotation extension using a Theiler Stage.
I tried Hoxa3 Mmus located_in nucleus existence_overlaps TS12 and the TS12 would not autocomplete.

In the graph if I try to add the TS12 it shows up in the add individual autocomplete, but when I click to add it, I get long error that essentially says it can't find the ID.

**Comment by vanaukenk** [comment]
@tmushayahama - Is there a PR for noctua-dev that addresses the missing XAO and TS stages?  Thx.

**Comment by vanaukenk** [comment]
This looks to be working okay for WBls, UBERON, and XAO (leaving Theiler stage ids out for the time being).

However, we seem to have lost ZFS terms.  I don't see them in either Noctua or noctua-amigo.

**Comment by vanaukenk** [comment]
ZFS terms have been added to GO-LEGO.  Will need to test this on production after the 2022-02-10 Noctua maintenance outage.

**Comment by vanaukenk** [comment]
ZFS life stage terms are available on the Noctua form autocomplete for 'existence overlaps' and 'existence starts and ends during' for CC terms.

However, the resulting extensions don't show up on the Noctua table and the extensions show on the graph with no label, just an id.

For now, I'll move this ticket back to testing-dev.

**Comment by vanaukenk** [comment]
@tmushayahama 
I can add extensions for the 'existence' relations and they show up fine on the graph now (i.e. the term labels are showing), but they still don't show on the Noctua form table on production beta. 
They _do_ appear in the table on noctua-dev, though, so I'm not sure why they aren't showing on production.

**Comment by vanaukenk** [comment]
Checked on prod and okay.
