### ISSUE TITLE
Add state 'internal test' to list of model states in Noctua form and Noctua landing page

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#158]
@tmushayahama 

Can you add 'internal_test' as a Noctua model state to the Noctua form and Noctua landing page?

It has already been added to the graph editor, but is not available for curators in the form or landing page.

Please see: https://github.com/geneontology/noctua/issues/621

Let me know if you have any questions.  Thanks.

**Comment by tmushayahama** [comment]
@vanaukenk something minor, any specific order of dropdowns and lists around Noctua so far

- Production
- Development
- Review
- Closed
- Delete
- Internal Test

**Comment by vanaukenk** [comment]
Thanks @tmushayahama   I think the order above is good for now.

I'd like to review the list of model states next year to see if they're all still consistent with our current thinking and workflows, but for now, let's keep the list and order exactly as you have it.

**Comment by vanaukenk** [comment]
Looks good on Noctua form (and graph, too).
Just waiting on having this new state added to the Noctua Landing page.

**Comment by vanaukenk** [comment]
Tested again on noctua-dev:
- Landing page
- Form editor
- Graph editor

All looks good; can be moved to production Nocuta.

**Comment by vanaukenk** [comment]
@tmushayahama 

I'm testing on production (beta) and don't see 'Internal test' displaying in the State drop-down list or models table on the landing page.  It _is_ there on noctua-dev, though (see above).

Did that update get included with PR #167 ?

Thx.

**Comment by vanaukenk** [comment]
From 2022-03-18 call:

Okay to update production Noctua landing page and Noctua form.

**Comment by vanaukenk** [comment]
Done
