### ISSUE TITLE
Evidence lost for Function after adding an input.

### ISSUE THREAD

**Issue by ukemi** [geneontology/noctua-form#162]
This morning in Noctua-dev I crated an model called Cblif (MGI:1202394) using the form editor. I made an MF annotation in the model with evidence. I saved the model and changed the title and state. Then I opened the model to add an input for the function and added evidence. When I saved the model, the evidence for the gene product enabling the function was lost.

**Comment by ukemi** [comment]
I just tried to add evidence manually to the function and I was unable to add it.

**Comment by ukemi** [comment]
We also noticed this during our training today and it is a serious issue. We tried to add evidence to an existing MF annotation and the original evidence was lost. Since this bug loses data, I am labeling it high priority.

**Comment by vanaukenk** [comment]
I also experienced this today when trying to add evidence for an 'occurs in' extension to an existing, evidenced MF.  I lost all of the original evidence I had on the existing MF.

**Comment by vanaukenk** [comment]
@tmushayahama 
I tested this issue on noctua-dev this morning and it does not appear to be fixed, i.e. adding a 'has input' extension in the Noctua form table to an existing MF annotation, removes the existing evidence from the 'enables by' assertion.
Let's look at this again together.

**Comment by vanaukenk** [comment]
@tmushayahama will work on this in the coming week

**Comment by vanaukenk** [comment]
We tested again on the 2022-06-30 workbenches call.  This is still an issue, with some new behavior from when the issue was originally reported.

Adding a protein as 'has input' to an MF removes evidence from the 'part of' BP associated with that MF.  Later, after a screen refresh, two pieces of evidence now appear on the BP.

Adding a chemical as 'has input' to an MF removes the MF evidence, initially put duplicate evidence on the BP, but then both of the BP evidences disappeared.

**Comment by vanaukenk** [comment]
Fix is on @tmushayahama noctua instance.
Will move to noctua-dev, test again there, and try to get out to production by next Tuesday.

**Comment by vanaukenk** [comment]
I've tested this issue on noctua-dev with model:  http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A62d7566e00000014

All seems to be working fine.

**Comment by vanaukenk** [comment]
Tested again on production - working as expected.
