### ISSUE TITLE
Happens_during extensions not displayed in Form

### ISSUE THREAD

**Issue by pgaudet** [geneontology/noctua-form#177]
Hello, 

I added an 'happens during' extension to the MF 'signaling receptor activity': the message saying that the annotation was updated was shown, but it didn't show on the form. 

However it it shown in the Graph Editor view. 

Model is: 62183af000001617

Thanks, Pascale

**Comment by vanaukenk** [comment]
I tested this on noctua-dev:  http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A62d7566e00000029

All seems to be working fine.

**Comment by vanaukenk** [comment]
Tested again on production - all seems to be working fine.
