### ISSUE TITLE
Make sure the new form allows for NOT annotations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#18]
We need to have the functionality to add a 'NOT' qualifier to annotations.

I think the simplest way to do this would be similar to what we have on the current form in the additional actions list.

We could make a top-level menu of 'Qualifier' and then have 'NOT' be available as the selection choice.  

This option would need to be available on every annotation line for the main aspects, Molecular Function, Biological Process, and Cellular Component (not on the additional contextual fields).

Also include 'NOT' for the BP only and CC only forms the same as above, i.e. only the main aspect, not the contextual fields.

@tmushayahama - let me know if you want to discuss further.

There is also a corresponding ticket on the noctua-form-legacy tracker here:
https://github.com/geneontology/noctua-form-legacy/issues/95

**Comment by tmushayahama** [comment]
@vanaukenk I was forgetting about the NOT. will look into it very soon. Will be back with more details soon.
