### ISSUE TITLE
BP search in Activity Unit and BP only forms returns some MF terms

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#19]
A search in the BP field of the Activity Unit and BP only forms returns some MFs, likely due to 'part of' links between MFs and BPs in the ontology.

![image](https://user-images.githubusercontent.com/1730534/65628262-19f82e00-df9f-11e9-9be2-109818c7f2f9.png)

We will want to restrict the BP field search solely to BP terms.

**Comment by tmushayahama** [comment]
@vanaukenk @kltm isn't this a neo issue. I just looked at the graph editor and the same kinda results. And its even displaying Uberon

![image](https://user-images.githubusercontent.com/2273929/65635244-ced91d80-df94-11e9-932d-eac7e79c666a.png)

**Comment by vanaukenk** [comment]
@kltm - the form is using 'is a' closure for the autocompletes, but we still seem to be getting 'part of' and other related terms.  

This happens on the graph editor, too.

Can we take a look at this to see what might be going on?

Thx.

**Comment by kltm** [comment]
@vanaukenk http://noctua-amigo.berkeleybop.org/amigo/search/ontology can be used to explore these issues. In general, AmiGO is extremely passive and what it displays, pushing most issues back to the loader or the ontology itself.

**Comment by cmungall** [comment]
It's hard to use the amigo view if the solr field is not exposed

But looking at the underlying golr query we can see that isa_closure is in fact there:

http://noctua-golr.berkeleybop.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&&q=*:*

This should never have been an issue. We should be using standard reusable javascript components with well-defined interfaces here.

**Comment by kltm** [comment]
@cmungall maybe:
<a href="http://noctua-golr.berkeleybop.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&&q=*:*">`http://noctua-golr.berkeleybop.org/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&&q=*:*`</a>
?

Ah, yes, we talked about this this morning with reference to https://github.com/geneontology/neo/issues/48 -- it looks like it *is* already there.

**Comment by tmushayahama** [comment]
@kltm @vanaukenk the neo ticket of this seems to be closed
