### ISSUE TITLE
Check publication date and author on PMIDs returned in reference field

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#22]
@tmushayahama 

Can you double-check the date that is returned when a PMID is entered into the reference field?

I just entered PMID:30789901 and the date was listed as January 31, 2019 although I don't see that date associated with the reference anywhere in the PubMed record:
https://www.ncbi.nlm.nih.gov/pubmed/30789901

Also, it looks like the last author is listed (e.g. Dennis H. Kim) but I thought we said we wanted the first author, et al. (e.g. Fletcher M., et al.).

Thanks!

**Comment by tmushayahama** [comment]
Fixed this using ncbi endpointaway from wikidata :) Temporarily putting all authors

![image](https://user-images.githubusercontent.com/2273929/66371240-88ea6500-e957-11e9-86f8-d8438f5280f1.png)

**Comment by tmushayahama** [comment]
@vanaukenk I think this is working now
