### ISSUE TITLE
Reimplanting table to ensure all data is read from Minerva

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#232]
We have successfully implemented a form for creating activities using a SHeX-like data structure. This dynamic form was essential due to the vast number of combinations of relationships and objects, making hard coding impractical.

However, we've encountered an issue with the table reading. The table reading was hard-coded, causing it to miss a significant amount of data fetched from Minerva. Specifically, if a relationship exists in SHeX but isn't recognized by the form (e.g., results_in_development), the data is not displayed correctly.

**Steps to Reproduce:**

- Navigate to the page where the table is displayed.
- Fetch data from Minerva that uses the SHeX format.
- Observe the discrepancies in the table's data representation

**Expected Result:**
The table should dynamically display all data fetched from Minerva based on the SHeX structure without any omissions.

**Actual Result:**
The table misses out on certain data points from Minerva due to its hard-coded reading mechanism.

**Recommendation:**
Reimplement the table reading steps to ensure it dynamically adapts to the SHeX data structure and accurately represents all data fetched from Minerva.

**Comment by kltm** [comment]
@tmushayahama @vanaukenk Just to clarify, is this part of a current project, or a proposal for something else?

**Comment by tmushayahama** [comment]
@kltm current project

**Comment by vanaukenk** [comment]
Yes, this work is within the scope of the current project and addresses issues like:  https://github.com/geneontology/noctua-form/issues/203

I've linked this ticket to the project.

**Comment by tmushayahama** [comment]
@vanaukenk @ukemi I think I have finished this one, I will go ahead and PR, so you can briefly take a look before workbench call. I think the table on ART can stay for now, that will bring lots of things. in other words if someone puts an unregistered edge
results_in_development GO:term, they will not edit it on ART

**Comment by vanaukenk** [comment]
For testing:

1. Check existing models to make sure that what is visible in the graph editor (i.e. what data exists for a model) is reflected in the Noctua form table

**Comment by vanaukenk** [comment]
I've made a test model for viewing relations display on the Noctua form table:

http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A64f8fbd000000030

The table view looks great to me based on this test model.

@ukemi @LiNiMGI

**Comment by ukemi** [comment]
Looks good! I think the indentation/nesting is clear.

**Comment by LiNiMGI** [comment]
Looks good! 
I also notice: after adding a cc only annotation to the test model, the line says "GP info not available"...
