### ISSUE TITLE
Fix ability to edit ontology terms/fields on the Noctua form table

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#236]
From testing on noctua-dev, @LiNiMGI found that we have now lost the ability to edit existing entries in fields on the Noctua form table.

This is essential for doing annotation reviews.

To recreate:

http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel%3A64f8fbd000000030

Go to this model and try to edit a field, e.g. an MF term, in the table.
Curators can replace with an existing term in the dropdown (from other annotations in the model), but cannot add a new term.

**Comment by tmushayahama** [comment]
After the dev server you can test this. More detail on the PR
https://github.com/geneontology/noctua-form/pull/237
