### ISSUE TITLE
BP Only table: Fix ability to edit relationship and Disable ability to edit root MF on the Noctua form 

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#238]
extending this issue https://github.com/geneontology/noctua-form/issues/236 we discovered that the table is not editing the relationship on BP Only. It should behave like the one on production 

![image](https://github.com/geneontology/noctua-form/assets/2273929/da8b70ab-f63c-430b-ae31-2a49bb230c45)

Disable editing root MF

tagging @linimgi @ukemi @vanaukenk @kltm @thomaspd

**Comment by LiNiMGI** [comment]
Thanks Tremayne, so you also disabled the ability to edit the relations even if in the current Noctua production table there is the ability to edit relations?

**Comment by LiNiMGI** [comment]
I also noticed for BP only annotations:
the three dots at the end of the table line disappeared for the molecular function line
if click on three dots for the gene product line and the process line, the "add" options also changed.
not sure whether there is request/reason for that...
