### ISSUE TITLE
Display GP information for CC only annotation 

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#239]
GP are not shown as below

![image](https://github.com/geneontology/noctua-form/assets/2273929/cbaf01e0-aea3-4407-8953-45a4449a7f5f)

tagging @LiNiMGI @ukemi @vanaukenk @kltm

**Comment by LiNiMGI** [comment]
thanks Tremayne! table view seems missing the CC term for cc only annotation, please see highlight in screenshot.
[Screenshot 2023-10-10 at 12.20.16 PM.pdf](https://github.com/geneontology/noctua-form/files/12859548/Screenshot.2023-10-10.at.12.20.16.PM.pdf)
