### ISSUE TITLE
Searching for human DDX58 returns different accessions with or without space

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#27]
Without a space after 'DDX58', only the UniProtKB isoform accessions are returned; with a space, the isoform and canonical accessions are returned.

**Comment by tmushayahama** [comment]
@kltm @vanaukenk any updates on autocomplete with space or this is working for now

**Comment by vanaukenk** [comment]
This issue has been addressed somewhat by increasing the number of entries returned in the autocomplete, but I'm going to leave it open so we make sure to consider the 'space' issue when working on the Noctua autocomplete more generally.

**Comment by vanaukenk** [comment]
This seems to no longer be an issue, so I'm closing for now.
