### ISSUE TITLE
Search annotation on isoforms

### ISSUE THREAD

**Issue by pmasson55** [geneontology/noctua-form#28]
Comparing the "search database" option between DDX58  (UniProtKB:O95786) and its isoform  (UniProtKB:O95786-1), it turns out that for the isoform no annotation could be retrieved.  Is it intended that no annotation is propagated to isoforms?

**Comment by vanaukenk** [comment]
This may be an issue with how these annotations are handled upstream.  Will need to check with @kltm @dougli1sqrd

**Comment by vanaukenk** [comment]
For reference wrt UniProtKB isoform annotations available with the :  https://github.com/geneontology/go-site/issues/1105

**Comment by vanaukenk** [comment]
@pmasson55 
Are there GO annotations specific to the DDX58 isoform (UniProtKB:O95786-1) that you expect to see that are not there in the Search Annotations function of the Noctua form?
GO wouldn't automatically propagate annotations from a parent protein to individual isoforms.

**Comment by pgaudet** [comment]
This seems to be a more general problem: 
https://github.com/geneontology/noctua-form/issues/192

I am not sure this is related to the isoform??

**Comment by pmasson55** [comment]
Hi,

Yes as Pascale said, we can merge the issue, as it seems that it's a more general problem, that some of annotations are not present when we search for existing annotation in the tool (isoform or not...). It's not a major issue, because if it s not present we can still search for the publication and the GO, it's just more convenient...

**Comment by vanaukenk** [comment]
Okay, I'm closing this ticket and we'll continue the work in #192
