### ISSUE TITLE
Display unique id or accession along with entity label or evidence on form

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#3]
Coming from https://github.com/geneontology/simple-annoton-editor/issues/22 with GP 

>  To clarify for curators what entity they are annotating, we will need to also display the unique id or accession associated with the gene name and species.

This will be the case for all other terms

@vanaukenk @thomaspd from last week's discussion. I just realized one problem with autocomplete which was the reason we didn't do this before.  Let'say you type **lipid transport** then it fills in with **lipid transport (GO:0006869).** However if you wanna change to something like lipid ... then you have to backspace all the **(GO:0006869)** before you can see results

**Comment by tmushayahama** [comment]
@vanaukenk any news on this one

**Comment by vanaukenk** [comment]
@tmushayahama - I think this is all working as expected and will close.
