### ISSUE TITLE
Check on status of DDANAT terms for autocomplete in the Noctua form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#33]
Hi @tmushayahama 

Petra from dictyBase is testing the form and would like to be able to autocomplete on her organisms' anatomy ontology, DDANAT.

The DDANAT terms are available in the graph editor, but not currently in the Noctua form.

Jim has recently done some work to bridge the DDANAT ontology with CARO so we should be okay on that front.

Can you check to see why the DDANAT ontology terms are not available in the Noctua form?

Thank you!

**Comment by tmushayahama** [comment]
@vanaukenk  I am not using CARO but UBERON:0000061. Should I use CARO. But how will I distinguish with Cell Type

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 

We may have to then bridge the DDANAT ontology the same way we did the WBbt, i.e. specifically bridge cells vs higher order anatomical structures.

We'll need to check with @jimbalhoff

**Comment by vanaukenk** [comment]
This is working in production.  We can re-open if dictyBase curators have any problems.
