### ISSUE TITLE
Make sure all autocomplete fields use only 'is a' closure

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#34]
We should remove the 'part of' closure for the autocomplete fields, as it will potentially be confusing and could possibly lead to annotation errors.

Confirmed with @ukemi  this morning.

@tmushayahama - let me know if you want to touch base about this at all.

Thx.

See also:  https://github.com/geneontology/noctua-form/issues/19

**Comment by tmushayahama** [comment]
it has been using isa_a closure. Maybe this is related to https://github.com/geneontology/noctua-form/issues/19
