### ISSUE TITLE
Form pre validation

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#35]
Form pre-validation or before save checks

- [x] GP is required
- [x] MF is required for Activity Unit and BP Only (root mf)
- [ ] if any term is provided, that term evidence is required
- [ ] if evidence is provided then reference is required
- [ ] DB: Accession check for reference

**Comment by pgaudet** [comment]
How does this relate to the ShEX ? Where are these rules being specified ?

**Comment by vanaukenk** [comment]
@tmushayahama 

Let's add these basic checks to this spreadsheet tomorrow when we talk:
https://docs.google.com/spreadsheets/d/1LZpoOm6IM9HVx1wL-Se3hERmHl9FbDm3taFUA3kmziE

Thanks!

**Comment by tmushayahama** [comment]
@vanaukenk all these check are working now except for CC only

**Comment by vanaukenk** [comment]
@tmushayahama 
This looks to be working on the CC only form, too.
