### ISSUE TITLE
Model Title naming guidelines and suggestions

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#36]
Currently if a model is not titled, the default naming is "enabled by [GP]"

Coming up with a title on the fly might be hard. Maybe a friendly non-blocking dropdown with few suggestions like below

![image](https://user-images.githubusercontent.com/2273929/68452057-14008a00-01a6-11ea-98b8-63dd0977acbe.png)

tagging @vanaukenk @thomaspd you once had a naming suggestion. Although noctua search will solve most problems, visually it is nice to have nice human readable titles

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 

I agree that human readable titles are nice to have.

We did have quite a lengthy discussion at one point about model naming conventions and IIRC, we decided that it would be difficult, at this time, to impose naming standards on curators.

I'm a little hesitant to provide a suggested title drop-down list, though, as I don't want curators to think that these are 'preferred' titles.

I think it might just be better to not allow curators to save without adding a free-text title of their choice.

@thomaspd - any thoughts on this?

Thx.

**Comment by goodb** [comment]
@vanaukenk Perhaps there could be a pop up or link out with/to some guidance about suggested naming conventions?   e.g. "A good title would include the biological process being described, etc.."  
it would be nice to avoid having lots of models named PMID 123.

**Comment by vanaukenk** [comment]
@goodb 

I think model titles will depend, in part, on workflow.  For example, after the imports, we'll have a whole bunch of models with MGI and WB gene ids as the title.

I agree, though, that if curators are creating a GO-CAM that represents a BP, they should include that BP in the title.

Perhaps what we will want is a guide to the different types of model titles explaining why they exist, and suggestions for adding titles to new models depending on what the curator is doing.  This might also be a good place to remind curators that the new search allows searching over a lot more model metadata so the titles don't have to include that.

**Comment by tmushayahama** [comment]
@goodb @lpalbou @vanaukenk @kltm I think this ticket will be much more useful after the search and api and so maybe this can be moved somewhere as it was lost :) and resume discussion later.

**Comment by vanaukenk** [comment]
Closing this ticket for now.
If, in the future, we feel we need to provide guidelines for model titles we can re-open with some actionable items.
