### ISSUE TITLE
Check 'Remove evidence' option in table view

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#40]
It doesn't look like the 'Remove evidence' option in the table view is working.  
When I select it, nothing happens to the evidence associated with the GO term.

**Comment by vanaukenk** [comment]
Action: remove the 'Remove evidence' option from the Table View

**Comment by tmushayahama** [comment]
@vanaukenk have removed it, but there is still minor logic problems with evidence. NF still needs to remove an evidence if there is more than 1.

**Comment by vanaukenk** [comment]
@tmushayahama - let's look at this tomorrow; I'm not quite sure I follow your comment but it will probably make sense when we look at it together.

**Comment by vanaukenk** [comment]
Closing this ticket; I think this is all done.  @tmushayahama - let me know if I'm mistaken.
