### ISSUE TITLE
Authentication and accessing Noctua Form

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#45]
Adding and editing should only be allowed for authenticated users. Although this will not happen, UI should be intuitive .Hiding form, edit links etc

**Comment by tmushayahama** [comment]
@vanaukenk now there are 3 different levels of feedback if you a user is not authenticated 

**A teaser**, shows the readonly form previews, activity form, causal relation editor form and cam detail form, etc
![image](https://user-images.githubusercontent.com/2273929/70278752-b5f5a100-1769-11ea-9925-ec2fe960ff8c.png)

**Lazy Action**, it shows that you can do the action but refuse the last minute. Only for button click actions, but not for text input.
![image](https://user-images.githubusercontent.com/2273929/70278072-6c588680-1768-11ea-8d58-1bf52156bec7.png)

Hidden **secret**, noone knows the functionality is there. The table doesn't have any edit buttons, havehidden all the menus
![image](https://user-images.githubusercontent.com/2273929/70278941-21d80980-176a-11ea-8a67-ead72ba504dc.png)

I will put the demo soon on the server, but lemme know which one is suited for which action

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
I like options 1 and 2 (teaser and lazy action).  I think it's good for people to know the edit functionality is there, but not allow any action until they've logged in.  Same for creating activities and BP/CC only.  Curators would not be able to enter any data until they're logged in.

**Comment by vanaukenk** [comment]
Done.
