### ISSUE TITLE
Hard-coded URLs exist in the software, rendering it unusable except in a single environment

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua-form#49]
There must be no hard-coded URLs in any workbench, except for invariant external resources. In this case, the hard-coded internal variables mean that the workbench can only be used in production (or some other specific environment).

See: https://github.com/geneontology/noctua-form/pull/47 - with this necessary PR, the workbench can only work in production -- if used in dev, it could cause user confusion or data corruption.

This is a *critical* issue and needs to be prioritized over any other work.

@tmushayahama @vanaukenk

**Comment by kltm** [comment]
Also see https://github.com/geneontology/noctua-form/issues/48

**Comment by vanaukenk** [comment]
Fixed.
