### ISSUE TITLE
Display 'occurs in' for BP in table for BP only annotation when CC is skipped

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#58]

**Comment by vanaukenk** [comment]
Tested and fixed on noctua-dev

**Comment by tmushayahama** [comment]
@vanaukenk we can change the title to emphasize that the table was not displaying other anatomical entities connected directly to MF by 'occurs in' if CC was skipped.

**Comment by vanaukenk** [comment]
@tmushayahama 
This information still doesn't seem to be displaying on the table, although it is correct in the graph editor.
Let's touch base on this one.

**Comment by vanaukenk** [comment]
The display works for Activity Unit.

**Comment by vanaukenk** [comment]
This looks okay on noctua-dev; ready to merge into production.

**Comment by vanaukenk** [comment]
Done.
