### ISSUE TITLE
Review side menu of curator actions

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#6]
From 2019-08-13 call

We looked at the side menu of curator actions for the form.  Two main considerations:

1. Available actions are as intuitive as possible to curators
2. We display only those actions that are essential in as neat a way as possible

General summary of considerations from @tmushayahama:

Mostly the option are categorized in the following actions for both the term and evidence:

Add (term or evidence) 
Remove, (nested term or any evidence) 
Clear Values, (each line, the whole term and its evidence(s) list)

Fill in helpers e.g.
quick fill in values like Root MF
cloning evidence 
search database
ND evidence

all other ones which on go rule (later)

Validation (shex, go rule (term, evidence combination) etc) 

Information: links to term or evidence page or maybe only on autocomplete

Help : link to documentation

**Comment by tmushayahama** [comment]
Added the nested nested menu

![image](https://user-images.githubusercontent.com/2273929/63387786-38915680-c35b-11e9-94f5-aca74bcf818a.png)

And for evidence category

![image](https://user-images.githubusercontent.com/2273929/63387876-6aa2b880-c35b-11e9-9531-ab9e332da59e.png)

tagging @vanaukenk @pgaudet 

And as discussed, will remove easy fill and combine Root Term with ND

**Comment by vanaukenk** [comment]
@tmushayahama 
I'm adding this to the 'In progress' column of the project.  These updates are not high priority, but if we can change the 'Easy Fill' to 'Add Root Term' and then have the 'Clear Values' remove the term and all associated evidence, that would be great.
Thx!

**Comment by tmushayahama** [comment]
@vanaukenk have fixed it, now on USC server. I temporarily change Add to Add an Extension. Let me know if its okay otherwise I will put back Add
