### ISSUE TITLE
Auto-size pop-up windows?

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#65]
@tmushayahama 

Would it be possible to auto-size pop-up windows?

For example, if the browser window is below a certain size, curators need to scroll in the Clone evidence box to click on 'Done' after they've selected a reference.

**Comment by vanaukenk** [comment]
Thanks, @tmushayahama 
This looks to be fixed on my browser and computer.
I'm going to ask Li Ni (MGI) to check on hers, too.

**Comment by vanaukenk** [comment]
The pop-up window still doesn't auto-size for Li.
I've asked her to join us on Monday (2020-03-16) so she can show us what she sees on her computer.

**Comment by vanaukenk** [comment]
From 2020-03-19 call with @tmushayahama:

The issue is with having to scroll horizontally.
Tremayne will address this and we can get Li to test, as well, on her machine.

**Comment by tmushayahama** [comment]
@vanaukenk I will fix all the popup issues. I was testing on a large display so for a smaller display it will be cut horizontally causing it to scroll

**Comment by vanaukenk** [comment]
For record keeping: Li tested this on noctua-dev and it was working for her there.

**Comment by vanaukenk** [comment]
Done.
