### ISSUE TITLE
Align allowed values for 'has input' and 'has output' with ShEx

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#66]
@tmushayahama 

Can we align the allowed values for 'has input' and 'has output' in the BP and MF ShEx shapes with what is allowed in the autocomplete in the form?

For Biological Process:
  has_input: ( @\<ChemicalEntity> OR @\<AnatomicalEntity> OR @\<ProteinContainingComplex> ) *;
  has_output: ( @\<ChemicalEntity> OR @\<AnatomicalEntity> OR @\<ProteinContainingComplex> ) *;

For Molecular Function:
has_output: ( @\<ChemicalEntity> OR @\<ProteinContainingComplex> ) *;
  has_input: ( @\<ChemicalEntity> OR @\<ProteinContainingComplex> ) *;

**Comment by tmushayahama** [comment]
@vanaukenk do you want to separate these into separate menu, i.e. 
Add Has input (Chemical)
Add Has input (Anatomical)
...

**Comment by vanaukenk** [comment]
I think the way you are doing it right now is good, i.e. just list parenthetically all the possibilities.

**Comment by tmushayahama** [comment]
i meant as in
Add Has Input (ChemicalEntity, AnatomicalEntity or ProteinContainingComplex) in one box or 

Add Has Input (ChemicalEntity)
Add Has Input (AnatomicalEntity )
Add Has Input (ProteinContainingComplex) in 3 separate boxes

**Comment by vanaukenk** [comment]
@tmushayahama 

I meant that parenthetically listing all of the possibilities in one menu item/box is okay.

In the future, we may try to design the form such that the actual inputs and outputs are restricted based upon the GO term selected, but we're not quite there yet.

Thx.

**Comment by vanaukenk** [comment]
I can enter all of the different kinds of inputs and outputs, but they don't display properly in the table (they look okay on the form).

For example, when I add two different inputs and outputs, it looks like only one of each is displayed twice.

See this test model:

http://noctua-dev.berkeleybop.org/workbench/noctua-form/?model_id=gomodel:5e431e7800000341

**Comment by vanaukenk** [comment]
@tmushayahama 
I was just double-checking this on noctua-dev and it looks like if there is more than one 'has input' or 'has output' entry, one of the two entries is duplicated.
Did the above commit fix this and is it just not on noctua-dev yet?
Thx.

**Comment by tmushayahama** [comment]
@vanaukenk I believe this ticket was for the values of the autocomplete on the form. 

**BP: is autocompleting to**
has_input: ( @<ChemicalEntity> OR @<AnatomicalEntity> OR @<ProteinContainingComplex> ) *;
has_output: ( @<ChemicalEntity> OR @<AnatomicalEntity> OR @<ProteinContainingComplex> ) *;

**MF is autocompleting on**
has_output: ( @<ChemicalEntity> OR @<ProteinContainingComplex> ) *;
has_input: ( @<ChemicalEntity> OR @<ProteinContainingComplex> ) *;

However for the table issue, it is more of general cardinality issue. It duplicates if there is not one to one. This one will be fixed soon

**Comment by vanaukenk** [comment]
@tmushayahama 
Okay, sounds good.  The allowed values on the form are all good, but we'll deal with the table display separately in #80 
Thx.

**Comment by vanaukenk** [comment]
@tmushayahama 
Just looking at this again, I'm wondering if we can wrap the text for the allowed extension values.  Right now, I can't see the full list on my screen.

**Comment by vanaukenk** [comment]
This is done.  We could improve the display in a separate ticket.
