### ISSUE TITLE
Disable Save in CC only version of form if any of the required fields are not filled in

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#67]
It is possible to save an annotation in the CC only version of the form, if the CC field is not filled in.

We need to implement the same functionality here as in other configs of the form whereby if a required field is not filled in, i.e. GO term, evidence code, reference, the curator cannot save and gets an explanation as to why.

Thx.

**Comment by tmushayahama** [comment]
@vanaukenk It will not be able to save GP occurs in CL, Uberon, Species) (i.e.if CC is skipped). So I let the checker be lenient for CC only. 

![image](https://user-images.githubusercontent.com/2273929/74785870-39e70180-5260-11ea-9b80-de939c0c77fc.png)

**Comment by vanaukenk** [comment]
Looks okay on noctua-dev; ready for master/production.

**Comment by vanaukenk** [comment]
Done
