### ISSUE TITLE
Add logout functionality to Noctua form

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#68]
After a user has logged in, they need to also be able to log back out :-)

The graph editor displays a logout button next to the user name, and we should add the same functionality to the Noctua form.

Thx.

**Comment by kltm** [comment]
This is actually quite important and has relevance to issues like:
https://github.com/geneontology/noctua/issues/636
https://github.com/geneontology/noctua/issues/641

**Comment by tmushayahama** [comment]
Added it inside the dropdown and now works with logging back 

![image](https://user-images.githubusercontent.com/2273929/74785517-5f274000-525f-11ea-8f77-72d2e6c7fdd6.png)

**Comment by vanaukenk** [comment]
@kltm @tmushayahama 

I'm testing the logout functionality on the form on noctua-dev and have a question about the message I see after I logout from the form:

![image](https://user-images.githubusercontent.com/1730534/76098457-7bcdb280-5f97-11ea-95bc-720bcb7926b2.png)

Contrast this with the message I see when I logout from the graph editor on noctua-dev or noctua:

![image](https://user-images.githubusercontent.com/1730534/76098740-031b2600-5f98-11ea-8ce2-c384a565e1b7.png)

Why does the message differ and what does the first message actually mean?

The model seems to be saved okay.

**Comment by kltm** [comment]
@vanaukenk In all likelihood, in the first, when you got to the barista page, your token was either already gone or had been otherwise destroyed. In the second image, you arrived at barista with a good token and it destroyed it for you. If this does not seem consistent or likely, we can explore it more.

**Comment by vanaukenk** [comment]
@kltm @tmushayahama   I'm not sure what the next steps here should be.  

I just tested again on noctua-dev by:

1) logging in from the landing page
2) getting (and noting) the token
3) migrating to the form and checking that I still have the same token
4) creating a single MF annotation and saving it
5) logging out from the form

Upon logout, I still get the same message about not being logged in.  This suggests that logout from the form is not working the same as logout from the graph editor, and I am assuming the latter is the correct behavior.

**Comment by vanaukenk** [comment]
Hmmmm.....one thing I'm noticing is that if I log out and then start all over again with a new noctua-dev page in my browser, I sometimes get the same token after logging into the form.
Still trying to figure out the exact conditions under which this happens.

**Comment by kltm** [comment]
@vanaukenk If you can wait until I have a little bandwidth, as I understand the underlying mechanism pretty intimately, I may be able to tease it out faster.

**Comment by vanaukenk** [comment]
Sounds good @kltm 
Just touch base when you have the time to work on this one.  Thx.

**Comment by kltm** [comment]
@tmushayahama What I think is going on here is that you are not actually logging out of barista and getting a cancellation on your current token--if you want to log out of the system, it is not as simple as erasing the token, but follows a pattern very similar to the login process, i.e.: "BARISTA_LOCATION/logout?return=USER_LOCATION_URL".

Essentially, to logout, do the same thing you did to login, but with a different path (/logout).

(Naturally, we could should bolt more of this into common libraries, etc., but this describes what we have at the moment.)

**Comment by tmushayahama** [comment]
Hi @kltm @vanaukenk , I am using the same url to logout you mentioned above. It is actually logging out but different messages. I even tested the token, and it will be inavlid after this logout API call.

![image](https://user-images.githubusercontent.com/2273929/76791137-75042400-677d-11ea-82d0-c7e9275fabfb.png)

**Comment by tmushayahama** [comment]
@kltm Aghh pardon my above, added barista_token to return url and fixed the issue thank you @lpalbou @vanaukenk PR soon

**Comment by kltm** [comment]
Me mistyping here (https://github.com/geneontology/noctua-form/issues/68#issuecomment-599692732) was not helpful. Apologies. I've amended it.

**Comment by tmushayahama** [comment]
@kltm now its its fixed, added barista_token as a param for logout and removed it from the reutnr url example
http://barista-dev.berkeleybop.org/logout?barista_token=b5pwryqtgmyitvngjgm5&return=http://localhost:8910/workbench/noctua-form/?model_id=gomodel:5e68429a00000048

**Comment by kltm** [comment]
@tmushayahama Generally, do not include tokens in URLs that are publicly available.

**Comment by vanaukenk** [comment]
Tested on noctua-dev and looks to be working fine now.

**Comment by vanaukenk** [comment]
Done.
