### ISSUE TITLE
Add three-letter ECO abbreviations to display of evidence code autocomplete values 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#7]
To help curators select the correct GO evidence code, it would be helpful to also provide the three-letter GO code in the autocomplete list.

I'm not sure how or where the information is stored for the evidence code autocomplete (i.e. as a dbxref like GOECO:IDA or 'has related synonym' IDA) but it is possible to search on nearly all of the three-letter GO codes and have the autocomplete return the correct code in the list.  It would just be nice for curators to be able to visually hone in on the GO three-letter codes more easily.

Also, the only GO code that doesn't present the correct option in the autocomplete list when I type the three-letter code is 'IDA' and I'm not sure why that is.  We need to address this, though, as IDA is very commonly used.

**Comment by vanaukenk** [comment]
GOECO codes are now available in the autocomplete pop-up window.

**Comment by tmushayahama** [comment]
@vanaukenk Can I remove the GOECO: and just display IDA, HDA for the below pic or it's needed?

![image](https://user-images.githubusercontent.com/2273929/64887005-5aa98c00-d61c-11e9-8bbc-08531824419a.png)

**Comment by vanaukenk** [comment]
@tmushayahama 
Yes, I think it would be fine to remove the GOECO prefix and just have 'IDA', 'IMP', etc in bold.

**Comment by vanaukenk** [comment]
@tmushayahama 
Just checking on the link outs in the autocomplete for the ECO codes.
Right now, clicking on an ECO id takes me to a page that says 'Need model_id' and nothing else :-(

**Comment by vanaukenk** [comment]
ECO in dbxrefs.yaml

https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml

**Comment by vanaukenk** [comment]
There isn't a url_syntax or example_url entry for ECO in the db-xrefs.yaml

@kltm - AmiGO currently goes to a GOC page for an ECO code, but I was thinking that for the Noctua form we would link out to an ECO page.  This is not high priority and I don't want to hold up release of Noctua 2.0 for it, but would like your opinion.  Thx.

**Comment by kltm** [comment]
@vanaukenk I think I'm fairly neutral about this--whatever would be of actual use/interest to curators in real contexts.
Technically speaking, ECO is part of the loaded ontologies for GO and appear in AmiGO as "exotic" ontology terms, if one removes the GO namespace filter. In the annotation search, they are not linked at all. (Maybe I'm missing other locations?)

**Comment by vanaukenk** [comment]
Closing this as the link outs from ECO ids are correctly going to ECO.

However, note that we still need to test the search by 'IDA' now that ECO has updated their synonyms:  https://github.com/geneontology/go-site/issues/1221
