### ISSUE TITLE
Change closure on Anatomy field to be CARO:0000000

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#71]
Hi @tmushayahama 

We need to change the closure on the Anatomy field from UBERON:0000061 to CARO:0000000

This will allow some of the anatomies, as they are currently bridged, to be available in the autocomplete.

Note that this isn't a perfect solution as cells are children of CARO:0000000, but it is an interim solution until we can figure out a different way to do this.

Thx.

**Comment by vanaukenk** [comment]
Thanks @tmushayahama 
This looks to be working fine.
I would like to have @sabrinatoro test this as well to make sure that Zfin is happy with how it works.

**Comment by sabrinatoro** [comment]
@vanaukenk I will test this later today. 
Could you tell me where I should be testing this, please? Thanks!

**Comment by vanaukenk** [comment]
Thanks @sabrinatoro!

Please test on noctua-dev:

http://noctua-dev.berkeleybop.org/

**Comment by sabrinatoro** [comment]
@vanaukenk @tmushayahama 
I think it works for ZFIN : The ZFA terms are available, and we know they are ZFA terms because we can see the ID. 

Is there a plan to allow BP-occurs in- cell or anatomy? Or should we use the high level term for "CC"? (it is not related to this case I think).

**Comment by vanaukenk** [comment]
Thanks @sabrinatoro !
The BP-occurs in- cell or anatomy is possible in the current form, but you have to go through CC to get there.
We are discussing whether to auto-populate CC when it is skipped in an annotation or to ask curators to fill in a CC to the best of their ability when making those statements.  
I'll create a separate ticket for that issue, so we can discuss further.
Otherwise @tmushayahama the original issue in this ticket looks to be addressed.  Thx!

**Comment by vanaukenk** [comment]
Done.
