### ISSUE TITLE
GOLr query to get individual types

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua-form#73]
Currently, one query is sent to GOLr to get the type of each individual, which can rapidly overload the search engine with 2000+ queries.

The queries will be redesigned to :
- [ ] use the fl parameter and retrieve only the data required
- [ ] retrieve the isa_closure for all tested terms in a single query, the JS code then getting [{ id: xxx, isa_closure: yyy }], allowing to get the types of each id tested

**Comment by tmushayahama** [comment]
@lpalbou @goodb  I will consult y'all soon with an example. There are some parts I still don't understand of GOLR 

## Example
For now lets say i have 20 IDs (a mix of GO IDs and CHEBI ids) and i wanna put them in buckets of BPs, CCs, MFs and GPs. How should I approach this in few requests. Not using aspect

### Approach 1: Brute Force
So far I am using brute force approach to ask every term and every isa_closure one to one i.e. 

ID1 4 times in this example
```ts
isaClosure(ID1, MF) -> false
isaClosure(ID1, BP) ->true
isaClosure(ID1, CC) -> false
isaClosure(ID1, GP) -> false
```

### Approach 2: ask all ids for one type
```ts
isaClosure (ID1, ID2, ID3, ..., MF)
```
However, i dont know how to read results so i can tell which of the IDs which one was not an MF

### Approach 3: Limiting Requests by predicate
used it on Noctua Form 1 but it was tiresome with small changes of the then shex (word of mouth specs :) )
if it is enabled_by I know object can be GP or Complex and subject of MF. so I will just ask 
```ts
isAClosure(objectId, GP)
isAClosure(objectId, Complex)
isAClosure(subjectId, MF)
```
### Approach 4: by prefix and aspect
Just to put it out here, which was used by Noctua Form 0

if it starts with UBERON, then it isaClosure of Uberon

**Comment by vanaukenk** [comment]
@tmushayahama - do we still need to keep this ticket open?

Thx.
