### ISSUE TITLE
Add 'Comment' to list of additional actions for each annotation line

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#75]
Placeholder for now.  Details coming.

**Comment by tmushayahama** [comment]
This appears in priority list of https://github.com/orgs/geneontology/projects/112, so discussion 

Comments were being read, but being hidden. We can expose them to the ui. What if we add inline like this prototype. If there is at least one comment you will see the icon with a tooltip of comments. Click to view more just like how the model level comments are implemented.

![image](https://github.com/geneontology/noctua-form/assets/2273929/39003434-fd06-4e71-beb3-08c881c88eaa)

and if you click it brings a popup similar to the model level comments. Then you can delete, view, add more etc

![image](https://github.com/geneontology/noctua-form/assets/2273929/b09b3c9a-991d-4d48-be47-43a9a9f1c664)

And to add a comment you either click the [...] button or the comment icon. The comment icon will appear if there is at least one comment to reduce clutter.

![image](https://github.com/geneontology/noctua-form/assets/2273929/0b5b9653-161f-4c5e-9eac-00391072f9c3)

Lastly, is anyone using the Ext, column, we can serve horizontal space

tagging @vanaukenk @ukemi Also tagging @pgaudet if this needed for vpe

**Comment by vanaukenk** [comment]
From 2023-08-31 workbenches call:
@ukemi @vanaukenk @LiNiMGI

Need to take a look on noctua-dev:
1. For non-causal models, e.g. a gene-centric model, add a comment on the graph (on the edge) and check the form
3. For non-causal models, e.g. a gene-centric model, add a comment on the form and check on the graph
4. Also, check for removing comments and editing comments

Note that the Noctua table is still a WIP for other issues.

**Comment by ukemi** [comment]
- [ ] Non-causal model testing  form->graph
- [ ] Non-causal model testing graph-> form
- [ ] Removing comments
- [ ] Editing comments

**Comment by ukemi** [comment]
Deleting

1. Deleting an existing comment at the MF does remove both lines.
2. Deleting a comment on an annotation extension works.

**Comment by ukemi** [comment]
Editing comments

1. Added and changed a comment to a CC only annotation. Followed progress on graph and form-worked
2. Added and changed a comment to a MF only annotation. Followed progress on graph and form-worked
3. Added and changed a comments to a BP annotation (MF and BP edges). Followed progress on graph and form-worked

**Comment by tmushayahama** [comment]
Thanks so much @ukemi for testing. lemme consider these into correcting. After fixing the form table, it will all be smooth. Very soon. Thank you

**Comment by vanaukenk** [comment]
2023-09-14
Tested functionality on workbenches call.  Good to go to production.
