### ISSUE TITLE
Split reference field out into two sections: db prefix and id number

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#8]
Right now, the form is not constraining how references are added which could result in mis-formatted reference entries.

We had proposed splitting the reference field out into two separate fields:

1) A list of valid dbxefs

2) A blank field for ids/accessions

There would need to be a value for each for SAVE to be enabled.

A bonus would be to retrieve a title for PMIDs to help the curator verify that they've entered the correct id.

**Comment by tmushayahama** [comment]
@vanaukenk can you list the reference prefixes which will go in a dropdown, i can hardcode them, I know PMID

**Comment by tmushayahama** [comment]
I found a list somewhere

- PMID
- DOI
- GO_REF
- PAINT_REF
- Reactome

Lemme know if this is all. and also give me an example of each. I assume it is all DB:number?

**Comment by pgaudet** [comment]
We don't want to manually assert 
PAINT_REF
Reactome
(not sure about GO_REF) -

Pascale

**Comment by vanaukenk** [comment]
For the form, definitely not PAINT_REF and Reactome.

I would keep GO_REF since they are sometimes used for different types of manual, sequence-based annotations.

**Comment by kltm** [comment]
@pgaudet Is this listed as a GO rule somewhere?

**Comment by pgaudet** [comment]
> Is this listed as a GO rule somewhere?

We can probably complete this rule and use it for this purpose ? 
https://github.com/geneontology/go-site/blob/master/metadata/rules/gorule-0000032.md
@vanaukenk would that work ?

**Comment by vanaukenk** [comment]
@pgaudet - Yes, we could add this information to gorule-0000032 to add another QC check.

**Comment by vanaukenk** [comment]
@tmushayahama 

The pop-up is great, but we still need to address two things:

1) The window should close when a curator clicks on the X or check box.

2) It is possible to select a value from the drop-down, e.g. PMID, not add anything to the identifier field, and still save.  This definitely shouldn't be allowed to happen.  If a curator selects a DB prefix value from the dropdown menu, they should be required to add an identifier before the pop-up window can be closed.

![image](https://user-images.githubusercontent.com/1730534/64439335-bcf01300-d097-11e9-8e7b-64627421c133.png)

For PMID and GO_REFs, the identifiers should only be digits.

For PMIDs, there can be 1-8 digits.

For GO_REFs, there can be 7 and the full list is here:
https://github.com/geneontology/go-site/tree/master/metadata/gorefs

For dois, there are digits but also additional characters.  Here's an example:  10.1038/s41467-019-11908-0
More information on doi syntax is here:
https://en.wikipedia.org/wiki/Digital_object_identifier

**Comment by pgaudet** [comment]
assigning myself as well to remember to edit the go-rule. 

Pascale

**Comment by tmushayahama** [comment]
@vanaukenk @pgaudet I was playing with a Reactome models and I saw the evidence Reactome:

![image](https://user-images.githubusercontent.com/2273929/64886768-c9d2b080-d61b-11e9-93e1-a68240e69177.png)

If there is no Reactome choice, then how to edit? Should I disable edit when NF see Reactome:?

**Comment by vanaukenk** [comment]
@tmushayahama 
Actually, all edit options should be disabled for Reactome models as the workflow here would be that if a curator wanted to work with an imported Reactome model they would first have to copy it and then make edits on the copied model.
Let's discuss further on today's call.

**Comment by goodb** [comment]
@vanaukenk I think he is just using these for testing purposes.  If and when the reactome models are moved out of dev, they should be tagged with a field (like non-editable..) such that the editor interface will know how to handle them.  This shouldn't be done in a Reactome-specific way, it should be a general purpose tag that we could apply to other models that we don't want curators to edit.

**Comment by vanaukenk** [comment]
This looks good now, too @tmushayahama 

One concern is that I can still enter an id in the free-form reference field without a DB prefix and the form will allow me to save.

Can we check that anything entered in the free-form reference field at least has the format:

text:text

I don't know if we can/should try to do more sophisticated checks, but this would be a help.

**Comment by vanaukenk** [comment]
Discuss best strategy at 2019-11-05 workbenches call.

**Comment by vanaukenk** [comment]
This all looks good.  Thx.
