### ISSUE TITLE
Save button on Form did not remove gear icon

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/noctua-form#83]
gomodel:5e72450500000780

Stacia made the model as development.  She tried to use Form to mark as production: clicked grey "development" button in header, opened lefthand menu, changed State and used blue save button.

Gear icon on main Noctua page did not go away (Mod column).  Saved again, no icon change.  I had to go to GE and use Save under the Model menu to remove the icon.

Perhaps this was because two people were looking at the model? Is me just looking at another curator's model recorded if I didn't change anything, and the model needs to be re-saved or something? I had the Form open when she was changing & saving the new State but I didn't change any info until I used the GE to Save.

**Comment by tmushayahama** [comment]
@kltm is there more to do on saving model. Below I am using the req.store 

![image](https://user-images.githubusercontent.com/2273929/77969578-d6a8b000-729e-11ea-9e53-6a26f0292613.png)

**Comment by kltm** [comment]
@tmushayahama That should be it. You can check the truth in the graph editor. Which interface is this showing up in? All interfaces, except for the graph editor, may require a refresh.

**Comment by tmushayahama** [comment]
Thank you @srengel @suzialeksander for finding and reporting this bug. Yes, it was not storing the model when model level metadata are changed. This will be fixed on the next build

@kltm I had forgotten to `req.store_model(modelId)` because I had separated saving form and model level annotations.

**Comment by kltm** [comment]
@tmushayahama Just confirming that you believe this is fixed on `dev`--we ran into this issue on production again and it caused a little bit of confusion.

@suzialeksander The workaround then is probably just to save while in the graph editor in the meantime.

**Comment by tmushayahama** [comment]
@kltm @suzialeksander  the production noctua form hasn't been updated for a while now. So the fix is not yet there

**Comment by kltm** [comment]
@tmushayahama Naturally, I just wanted to confirm that it was closed on noctua-dev--I wasn't sure of the "state" is this is in no current project, etc.
