### ISSUE TITLE
loading indicators when saving and loading form

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#84]

**Comment by tmushayahama** [comment]
@kltm what is the minerva way of handling similar to 
finalize: (whether a request has failed or passed) or after the promise has been rejected or resolved. I want to set `loading = false` in there

what function shout I register and to which key?

![image](https://user-images.githubusercontent.com/2273929/78194940-49e32b00-7433-11ea-8909-5a9b857a57fb.png)

**Comment by kltm** [comment]
If I'm following you, the closest would be a `postrun` tag, which would run at the end no matter what.

**Comment by kltm** [comment]
Essentially, that's what "shieldsUp" and "shieldsDown" are playing with.

**Comment by tmushayahama** [comment]
@vanaukenk just to clarify that the phrases makes sense or too technical. Any nicer phrases besides "loading..."

**First one is Sending Request to get the model to barista (mostly quick)**
![image](https://user-images.githubusercontent.com/2273929/80655781-5e1b4780-8a34-11ea-9ca2-2231936388f0.png)

**And the second one which takes longer is like resolving, sending GOLR eequest for types**
![image](https://user-images.githubusercontent.com/2273929/80655819-78edbc00-8a34-11ea-946c-524506ce68f8.png)

**Comment by vanaukenk** [comment]
I think this is all working fine now.
Will close.
