### ISSUE TITLE
Increase number of results shown in autocomplete to 50

### ISSUE THREAD

**Issue by lpalbou** [geneontology/noctua-form#87]
At the moment, the autocomplete only show the 10 best results. Considering golr has been problematic to find the best results, this prevent users to find for instance the gene they were looking at.

Increase the limit to at least 50. If we have feedback it's not sufficient, this will be further increased.

Note: this can be affecting also the autocomplete on the landing page, in which case, please increase the cap their too. Thanks !

**Comment by cmungall** [comment]
Just chatting with @lpalbou, if the curators are requesting 50 cutoff, go ahead. However, I am convinced the need for as many as 50 is driven by something sub-optimal that can be improved. It may be an issue with the upstream gpi, with the golr indexing, with the AC implementation. If there are examples of cases where people need the 50 I can comment

**Comment by vanaukenk** [comment]
Let's discuss this ticket on the workbenches call tomorrow.
There may definitely be some things that could be optimized, but depending on the search string, 10 returns can be too small.  There are work-arounds for the current search behavior, but if we can improve the search experience, let's do it.

**Comment by vanaukenk** [comment]
@lpalbou 

We discussed this ticket on the workbenches call.

I'd like to just clarify with you whether the increase to 50 was in direct response to the search issue that Patrick was having, or was 50 chosen in response to another issue.

I think with the current search, an increase is warranted, but just want to make sure I'm clear on what we're responding to and why.

Thx.

**Comment by cmungall** [comment]
is this to deal with isoforms? it seems an even better solution would be to prioritize non isoform / gene-centric entries

**Comment by vanaukenk** [comment]
@cmungall 

I think this change does address the >10 isoform issue, but we should discuss further on a workbenches call to make sure we've considered the various use cases and before making any other changes.

I'd advocate annotating (and prioritizing in search returns) a gene or gcrp identifier whenever possible, but we will definitely still need to support isoform annotation and in some cases, e.g. C. elegans unc-52, there are more than 10 isoforms, so the current implementation of the autocomplete doesn't return the full list.

A current workaround is for curators to type in the CURIE, e.g. WB:CE15028, but we've already gotten feedback that this is tedious and inefficient.

Happy to discuss further, though, as this is very important for UX.

**Comment by vanaukenk** [comment]
Closing this ticket for now as the original issue has been addressed.
Future work on the autocomplete will be captured in separate tickets.
