### ISSUE TITLE
Navbar for Noctua Form to resemble that of GO site or

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#89]
@vanaukenk any thoughts on the below? Keeping the title on the line will squeeze things. And making a title row will add to the height.

But it cuts the right
![image](https://user-images.githubusercontent.com/2273929/79014900-ab388780-7b20-11ea-870e-b4dea11fb2d9.png)

A compromise might be making it like the new landing page result row on results

![image](https://user-images.githubusercontent.com/2273929/79017352-f5703780-7b25-11ea-9402-61fd603ec95c.png)

or even better, truncate the title and the whole title is available upon opening model detail side menu
![image](https://user-images.githubusercontent.com/2273929/79017525-64e62700-7b26-11ea-8e94-b76fbae16dc5.png)

**Comment by vanaukenk** [comment]
@tmushayahama 
Looking at the various options again, I'd say let's go for option 2, with the full title on the same line as the other model metadata.
That would be consistent with title display in the table on search.

**Comment by vanaukenk** [comment]
This work is finished; all looks good.
