### ISSUE TITLE
Evidence not saved on the MF enabled by GP

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#93]
Other related issues
 https://github.com/geneontology/noctua-form/issues/79#issuecomment-615443120
https://github.com/geneontology/noctua-form/issues/80#issuecomment-615463360

@vanaukenk it turns a lil hiccup on the enabled by edge on the.

**Comment by tmushayahama** [comment]
@vanaukenk this issue is now fixed on dev

**Comment by vanaukenk** [comment]
Checked and appears to be fixed.
