### ISSUE TITLE
Field value reuse in models

### ISSUE THREAD

**Issue by cerivs** [geneontology/noctua-form#99]
It would be nice to be able to keep using the same sets of PMIDs in a model created in the form so we don't repeatedly  have to keep navigating away from the form to get the PMID.  Perhaps a list of the PMIDs used in the mode could be accessible in the reference adding bit of the form.

**Comment by tmushayahama** [comment]
hi @cerivs so far you can use the **clone evidence feature** to achieve this, not yet few clicks

on the more options button [...], **select** evidence, the **click** clone evidence
![image](https://user-images.githubusercontent.com/2273929/81356193-75d27b80-9085-11ea-91b7-ef55400ba9e3.png)

However it will copy both evidence and reference
![image](https://user-images.githubusercontent.com/2273929/81356253-9d294880-9085-11ea-9a6c-daf5d6784e23.png)

You can then simply remove evidence value after and add a different one but keeping the reference
![image](https://user-images.githubusercontent.com/2273929/81356445-0a3cde00-9086-11ea-9212-6930d65bbb42.png)

tag @vanaukenk

**Comment by cerivs** [comment]
Thanks @tmushayahama.   That is helpful if rather buried in sub-menus.  The real issue is that I'm adding different evidence  from the same publication.  So I have evidence for protein interaction and evidence base on a mutant phenotype I can't just pick the most recently used PMID.

**Comment by vanaukenk** [comment]
Thanks @cerivs 
We will brainstorm and come up with some ideas for how to re-use evidence and references more easily (perhaps splitting the evidence code and reference apart so they can be chosen independently).

**Comment by vanaukenk** [comment]
See also:
https://github.com/geneontology/noctua/issues/308
https://github.com/geneontology/noctua/issues/426
https://github.com/geneontology/noctua/issues/445
https://github.com/geneontology/noctua/issues/521

**Comment by vanaukenk** [comment]
From 2020-09-11:

1) Add a header to the pop-up windows: "Previously used in this model"
2) For the previously used References and Withs, no filter (once a user starts typing, no pop-up) since these are not autocomplete fields
3) For the Reference field, when a user clicks on the 'New Reference' (+) , the previously used pop-up disappears

**Comment by vanaukenk** [comment]
If there is an error in the model such that a term is included in the re-use list, but that term is there by mistake, e.g. a BP term in the MF list, for now we will keep the incorrect term in the list until we have a better way to handle invalid models in the form.

**Comment by vanaukenk** [comment]
@tmushayahama - just a minor thing, but if possible,  it'd be nice to include the bolded, three-letter ECO code abbreviation in the re-use list the same way that it is shown in the original autocomplete.

For example, the drop-down list shown below would have 'IDA' in bold between the label and the id:

![image](https://user-images.githubusercontent.com/1730534/94286320-d96d2080-ff22-11ea-8596-c53585821b74.png)

**Comment by vanaukenk** [comment]
@tmushayahama 
There are just a few minor changes to this ticket based on the comments directly above, but otherwise this is working fine on dev.
Let me know if you want to touch base to go over anything.

**Comment by vanaukenk** [comment]
@tmushayahama 

I'm testing on dev and wondering if you've had a chance to look at the two comments above:
https://github.com/geneontology/noctua-form/issues/99#issuecomment-691231332
https://github.com/geneontology/noctua-form/issues/99#issuecomment-698997917

If we can address those small issues, I'll test again and move this into clearing.  Thx.

**Comment by vanaukenk** [comment]
@tmushayahama 
1) investigate adding three-letter, bolded ECO code to existing list
2) add a header to the pop-up windows: "Previously used in this model"
3) hide existing list of references when a curator clicks to add a new reference
